# Generated by Django 4.1.5 on 2023-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do cliente', max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, help_text='CPF do Cliente', max_length=11, null=True, verbose_name='Cpf')),
                ('cnpj', models.CharField(blank=True, help_text='CPNJ do Cliente', max_length=14, null=True, verbose_name='Cnpj')),
                ('endereco', models.CharField(help_text='Endereco do cliente', max_length=50, verbose_name='Endereco')),
                ('telefone', models.CharField(help_text='Telefone do Cliente', max_length=11, verbose_name='Telefone')),

            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
