# Generated by Django 4.1.5 on 2023-01-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=1, help_text='Email do cliente', max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
